### ISSUE TITLE
missing language files

### ISSUE THREAD

**Issue by manu37** [cmb69/fa_xh#32]
While setup the demo page I noticed the three missing language files of the most common C_XH languages: cs, da and sk. Just setup these langfiles (with en content?) might suffice. Otherwise Tiny4 throws an error message.

**Comment by cmb69** [comment]
Isn't it possible to tell TinyMCE 4 to fall back to some language (e.g. `en`)? How is the [`languages` parameter](https://www.tinymce.com/docs/api/tinymce/tinymce.addonmanager/#requirelangpack) supposed to work?

**Comment by cmb69** [comment]
Okay, I've checked the `languages` parameter. Apparently, one has to add all available languages there. Not very dev-friendly, but at least a viable solution.
