### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by olape-git** [cmb69/fa_xh#37]
https://github.com/cmb69/fa_xh/blob/03f60cdd885a6e01cb48d46a1bc43b66a1dc53c6/languages/de.php#L3
https://github.com/cmb69/fa_xh/blob/03f60cdd885a6e01cb48d46a1bc43b66a1dc53c6/languages/en.php#L3

**Comment by cmb69** [comment]
Nope, not a type. That's the name of that icon.

**Comment by olape-git** [comment]
sorry,
i guessed from the name that it was the alternate text to the logo.

**Comment by cmb69** [comment]
It is, but the name of that logo is "Fort Awesome". See also https://fortawesome.com/ and https://github.com/cmb69/fa_xh/pull/27.
